import Head from 'next/head'
import TopCourseList from '../components/TopCourseList/TopCourseList'
import Layout from "../components/Layout/Layout";


const Home = (): JSX.Element => {
    return (
        <div>
            <Head>
                <title>Beauty Schools</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <TopCourseList/>
        </div>
    )
}

Home.layout = Layout
export default Home
