import type {NextPage} from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import TopCourseList from '../components/TopCourseList/TopCourseList'


const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Beauty Schools</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <TopCourseList/>
        </div>
    )
}

export default Home
